logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: INFO
        transaction: INFO
        web.client.RestTemplate: INFO

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        redirect-uri-template: ${gpfd.redirect-uri-template}
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
  datasource:
    read-only:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:MOJFIN
      username: sa
      password:
      driver-class-name: org.h2.Driver
    write:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:MOJFIN
      username: sa
      password:
      driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /swagger.yml

gpfd:
  datasource:
    write:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:MOJFIN;DB_CLOSE_DELAY=-1;MODE=Oracle
      username: sa
      password:
      driver-class-name: org.h2.Driver
    read-only:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:MOJFIN;DB_CLOSE_DELAY=-1;MODE=Oracle
      username: sa
      password:
      driver-class-name: org.h2.Driver


  redirect-uri-template: http://localhost:8080

