gpfd:
  url: https://uat.get-legal-aid-data.service.justice.gov.uk
  redirect-uri-template: ${gpfd.url}/login/oauth2/code/gpfd-azure-uat

  # Base URI for the key information needed to validate a JWT
  # The JWT Spring decoder automatically appends .well-known/openid-configuration
  jwks-uri: https://sts.windows.net/${spring.cloud.azure.active-directory.profile.tenant-id}/

  # MOJFIN database config
  datasource:
    read-only:
      url: ${MOJFIN_DB_URL}
      username: ${MOJFIN_DEV_READ_USERNAME}
      password: ${MOJFIN_DEV_READ_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
    write:
      url: ${MOJFIN_DB_URL}
      username: ${MOJFIN_DEV_WRITE_USERNAME}
      password: ${MOJFIN_DEV_WRITE_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver

spring:
  liquibase:
    enabled: true
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID_UAT}
        credential:
          client-id: ${AZURE_CLIENT_ID_UAT}
          client-secret: ${AZURE_CLIENT_SECRET_UAT}
        redirect-uri-template: ${gpfd.redirect-uri-template}
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read

server:
  port: 8080
  forward-headers-strategy: native # not sure if needed
  shutdown: graceful
  servlet:
    session:
      cookie:
        secure: true
