# Azure AD and Graph config
#spring:
#  cloud:
#    azure:
#      credential:
#        client-secret: ${AZURE_CLIENT_SECRET}
#        client-id: ${AZURE_CLIENT_ID}
#      profile:
#        tenant-id: ${AZURE_TENANT_ID}
#
#      active-directory:
#        enabled: true
#        authorization-clients:
#          graph:
#            scopes:
#              - https://graph.microsoft.com/User.Read
#        post-logout-redirect-uri: /

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        redirect-uri-template: https://laa-pay-for-la-dev.apps.live.cloud-platform.service.justice.gov.uk/login/oauth2/code/gpfd-azure-dev
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read

#server:
#  port: 8080
#  forward-headers-strategy: native