# Azure AD and Graph config
spring:
  cloud:
    azure:
      credential:
        client-secret: thiswouldbeasecret
        client-id: thiswouldbeaclientid
      profile:
        tenant-id: thiswouldbeatennantid
  datasource:
    #    url: jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:oracle:thin:@RDS.MOJFIN.LAA-DEVELOPMENT.MODERNISATION-PLATFORM.SERVICE.JUSTICE.GOV.UK:1521/MOJFIN
    username: blah
    password: blahword
    driver-class-name: oracle.jdbc.OracleDriver


#      active-directory:
#        enabled: true
#        authorization-clients:
#          graph:
#            scopes:
#              - https://graph.microsoft.com/User.Read
#        post-logout-redirect-uri: /

#server:
#  port: 8080
#  forward-headers-strategy: native