#SSL configuration
logging:
  level:
#    root: DEBUG
    org.springframework: INFO
#    org.springframework.security: INFO #TRACE
    log4j.rootLogger: trace


server:
  port: 8443
  shutdown: graceful
  servlet:
    session:
      cookie:
        secure: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: testCert
    key-password: password



# Azure AD and Graph config
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        redirect-uri-template: https://laa-pay-for-la-dev.apps.live.cloud-platform.service.justice.gov.uk/login/oauth2/code/gpfd-azure-dev # dev
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read

  # Database config
  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:oracle:thin:@RDS.MOJFIN.LAA-DEVELOPMENT.MODERNISATION-PLATFORM.SERVICE.JUSTICE.GOV.UK:1521/MOJFIN
    username: ${MOJFIN_DEV_USERNAME}
    password: ${MOJFIN_DEV_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver







