# Azure AD and Graph config
spring:
  cloud:
    azure:
      credential:
        client-secret: ${AZURE_CLIENT_SECRET}
        client-id: ${AZURE_CLIENT_ID}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:oracle:thin:@RDS.MOJFIN.LAA-DEVELOPMENT.MODERNISATION-PLATFORM.SERVICE.JUSTICE.GOV.UK:1521/MOJFIN
    username: ${MOJFIN_DEV_USERNAME}
    password: ${MOJFIN_DEV_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver


#      active-directory:
#        enabled: true
#        authorization-clients:
#          graph:
#            scopes:
#              - https://graph.microsoft.com/User.Read
#        post-logout-redirect-uri: /

#server:
#  port: 8080
#  forward-headers-strategy: native