logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: INFO
        transaction: INFO
        web.client.RestTemplate: INFO