gpfd:
  redirect-uri-template: https://laa-pay-for-la-dev.apps.live.cloud-platform.service.justice.gov.uk/login/oauth2/code/gpfd-azure-dev
  # Note,"gpfd-azure-dev" is also known as the Oauth2 'registrationId'

#SSL configuration
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
#    org.springframework: INFO
#    org.springframework.security: INFO #TRACE
    org.springframework.web.client.RestTemplate: DEBUG


server:
  port: 8443
  forward-headers-strategy: native # not sure if needed
  shutdown: graceful
  servlet:
    session:
      cookie:
        secure: true
  ssl:
    key-store: classpath:gpfd-ssl-keystore.p12
    key-store-password: ${SSL-DEV-KEY-STORE-PASSWORD}
    key-store-type: PKCS12
    key-alias: gpfd-dev-ssl-key
    key-password: ${SSL-DEV-KEY-STORE-PASSWORD}



# Azure AD and Graph config
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        redirect-uri-template: ${gpfd.redirect-uri-template}
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Files.ReadWrite.All

#  security:
#    oauth2:
#      client:
#        registration:
#          azure:
#            client-id: ${AZURE_CLIENT_ID}
#            client-secret: ${AZURE_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            redirect-uri: ${gpfd.redirect-uri-template}
#            scope: openid, profile, https://graph.microsoft.com/User.Read, https://graph.microsoft.com/Files.ReadWrite.All
#            client-name: Azure
#            client-authentication-method: post
#        provider:
#          azure:
#            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: name
#            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys


  # Database config
  datasource:
    #    url: jdbc:oracle:thin:@localhost:1521:xe
    url: jdbc:oracle:thin:@RDS.MOJFIN.LAA-DEVELOPMENT.MODERNISATION-PLATFORM.SERVICE.JUSTICE.GOV.UK:1521/MOJFIN
    username: ${MOJFIN_DEV_USERNAME}
    password: ${MOJFIN_DEV_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver







