logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: INFO
        jdbc: DEBUG
        #          core:
        #            JdbcTemplate: INFO
        #            StatementCreatorUtils: INFO
        transaction: INFO
        web.client.RestTemplate: INFO