apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      serviceAccountName: example-name #This relates to the IRSA module in our namespace, within the cloud-platform-environments repo
      containers:
        - name: example
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8080


# This is a generic file that creates a Kubernetes deployment in our namespace. A deployment is a collection of pods
# that runs one or more containers. In this application, currently only one container is run in the pod.